apiVersion: v1
kind: Service
metadata:
  name: gitlab-postgresql
  namespace: jenkins
  labels:
    name: gitlab-postgresql
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    name: gitlab-postgresql
